version: "3.7"
services: 
  node:
    image: "node:10.16.3"
    volumes: 
      - ./:/user/src/app
    working_dir: /user/src/app
    expose: 
      - "9001"
    ports: 
      - 3001:3001
    # networks: 
    #   - default
    command: 
      yarn start
    container_name: allinpay
  # networks: 
  #   default:
  #     external:
  #       name: backend
