version: "3"

services:
  node:
    image: "node:10.16.3"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    expose:
      - "3000"
      - "50050"
    ports: 
      - 3000:3000
    networks:
        - application
        - database
    command: yarn start
    container_name: allinpay
networks:
  database:
    external: true
  application:
    external: true
